# Generated by Django 4.2.4 on 2023-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=200)),
                ("des", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Cars",
        ),
    ]
